version: "2"
services:
    mongodb:
           image: mongo
           restart: always
           container_name: mongodb
           volumes:
               - ./data-node:/data/db
           ports:
               - 27017:27017
           command: mongod --noauth
           networks:
               - webappnetwork
networks:
    webappnetwork:
        driver: bridge